# Generated by Django 3.0.8 on 2020-07-18 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('animal', models.CharField(max_length=100)),
            ],
        ),
    ]
